### ISSUE TITLE
Consolidate `liferay-jest-junit-reporter` output

### ISSUE THREAD

**Issue by jbalsas** [bryceosterhaus/liferay-npm-tools#1]
Based on offline conversations with @john-co who's been analyzing the way to [Organize frontend-js unit test results](https://issues.liferay.com/browse/LRQA-44612), we need to update the output of our [`liferay-jest-junit-reporter`](https://github.com/jbalsas/liferay-jest-junit-reporter) so:
>
> For organizing frontend-js unit test results: https://issues.liferay.com/browse/LRQA-44612
>
> QAE can organize it on PR tester but will need your help modifying:
https://github.com/jbalsas/liferay-jest-junit-reporter/blob/master/index.js to include <failure> tags for test failures. And any additional information (component name), might need to be included in the test name. For component names, maybe it might be good to utilize the package name or other fields for additional information. This may also be a good place to start thinking about standardizing how js packages and classes are named to have a consistent structure on jenkins.

> QAE will need:
> 1. TEST-frontend-js.xml to include <failure> children tags for tests that fail.
> 2. Any additional information you would like to see displayed (ie: component name) to be included somehow in the TEST-frontend-js.xml for each test. Maybe include in the test name?
> 3. not a requirement but a good idea: define a consistent naming structure for package and class names of js tests.
> 
> Background:  Jenkins is setup to take information only from the TEST*.xml file. QAE is able to display > information that's provided in the TEST*.xml and can specify what portions of the js test log output. 

> For requirement 1 and 2: Here's an example TEST-frontend-js.xml output I would like to see from ManagementToolbar.es.js test. I've included the original and the proposed output files. I've included comments to clarify the areas that will need to be modified. Let me know if you have any questions
>
> Current ManagementToolbar.es.js TEST-frontend-js.xml output: https://github.com/john-co/liferay-portal/pull/41/commits/9f347479300127b3a519b69a61b0f295f38ebc65#diff-2bc85b86812a9f8ad670d145322be496
>
> Proposed modifications to TEST-frontend-js.xml: https://github.com/john-co/liferay-portal/pull/42/commits/58ea3d17ad9a67d93bed903424a7926218bf0fa5#diff-2bc85b86812a9f8ad670d145322be496 (edited) 
>
> For requirement 3:  Naming convention, I would suggest PascalCasing the *.es.js file names and add Test to the end like this: ManagementToolbarTest.es.js. I think this will also make identifying the test suite easier on jenkins.

**Comment by bryceosterhaus** [comment]
Fixed https://github.com/bryceosterhaus/liferay-npm-tools/pull/4
