### ISSUE TITLE
Allow passing env params

### ISSUE THREAD

**Issue by andresfulla** [bryceosterhaus/liferay-npm-tools#7]
It'd be great to be able to pass environment variables to the build. Or have a `liferay-npm-tools start` or `liferay-npm-tools dev` task with some standardised environment variables.

My use case is a state tree logger I want to be present in development builds, but not in production ones.

**Comment by bryceosterhaus** [comment]
Oh interesting, so you would want to possibly build and deploy a module without having `process.env.NODE_ENV = 'production';`? This should be possible. I will probably leave `production` as default, but allow for some customization.
